# [START django_app]
runtime: python37
service: parivate-google-translate
env_variables:
  PROJECT_ID: 'yutty-argolis'
  BUCKET_NAME: 'yutty-translate-demo'
  API_KEY: 'AIzaSyA9aUQUboMVShUEGVMEIHrd_q_N2c_MR1U'
entrypoint: gunicorn -b :8080 app:app